apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: user
    secureJsonData:
      password: password
    jsonData:
      database: fraud_db
      sslmode: 'disable'
      timescaledb: false
